### ISSUE TITLE
URL padding

### ISSUE THREAD

**Issue by hilarylewis92** [kelsiebesingeryeh/kb-comp-challenge-1#6]
The problem: uneven spacing on the URL wrapper. See image for ref. 
<img width="242" alt="Screen Shot 2020-12-31 at 9 57 26 AM" src="https://user-images.githubusercontent.com/18403177/103419104-da7ba280-4b4e-11eb-892d-742ced115f3d.png">

Possible solution: Consider removing the set height on .URL and add padding as a px or rem to account for more even spacing.
<img width="238" alt="Screen Shot 2020-12-31 at 9 57 11 AM" src="https://user-images.githubusercontent.com/18403177/103419130-f7b07100-4b4e-11eb-8746-c8171aac90a5.png">
<img width="247" alt="Screen Shot 2020-12-31 at 9 57 18 AM" src="https://user-images.githubusercontent.com/18403177/103419134-fa12cb00-4b4e-11eb-998b-f4fd91bb599a.png">

**Comment by kelsiebesingeryeh** [comment]
Got it. this has been fixed.
