### ISSUE TITLE
Card content text stacking issue

### ISSUE THREAD

**Issue by hilarylewis92** [kelsiebesingeryeh/kb-comp-challenge-1#7]
The problem: on viewport ~600px - ~800px the stacking of the card content text is on top of each other.
<img width="746" alt="Screen Shot 2020-12-31 at 10 02 42 AM" src="https://user-images.githubusercontent.com/18403177/103419311-bec4cc00-4b4f-11eb-948b-1ced311f749a.png">

Possible solution: consider adding line-height to your p tags.

**Comment by kelsiebesingeryeh** [comment]
thank you!
